version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: chatapp
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
